### ISSUE TITLE
Add in support for custom schemes

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#11]
We need to support the custom schemes that version 1 supports: `ftcms`, `fticon`, `fthead`, `ftsocial`, `ftpodcast`, `ftlogo`.

These map to various Git repositories, and there are a couple of options for doing this:

1. On deploy, all of the required repositories are installed on the server and custom schemes map to the created folder of images. This is similar to way v1 of the Image Service works. This method is complicated by the fact that we need to apply transforms through proxying to a third-party – we'd need to publicly expose the raw images and then hit the image service twice to load them:

  ```
  > https://image-service/v2/images/raw/fticon:cross?format=png
  [ expands to ]
  > https://image-service/v2/images/raw/https%3A%2F%2Fimage-service%2Fv2%2Fimages%2Fsource%2Ffticon%2Fcross.svg?format=png
  [ proxies to ]
  > https://third-party/image/https%3A%2F%2Fimage-service%2Fv2%2Fimages%2Fsource%2Ffticon%2Fcross.svg?format=png
  [ third-party hits the image service again to request the icon ]
  ```

2. On request, the URL is mapped to a _different_ publicly hosted version of the images. This is very similar to option 1 except that the image service itself wouldn't be responsible for serving the images as well as proxying them:

  ```
  > https://image-service/v2/images/raw/fticon:cross?format=png
  [ expands to ]
  > https://image-service/v2/images/raw/https%3A%2F%2Fother-service%2Ffticon%2Fcross.svg?format=png
  [ proxies to ]
  > https://third-party/image/https%3A%2F%2Fother-service%2Ffticon%2Fcross.svg?format=png
  [ third-party hits the other service to request the icon ]
  ```

3. On request, the URL is mapped to an image that has been uploaded to the third party already. This would require us to build an image uploader as [outlined in the original proposal](https://docs.google.com/drawings/d/1fC07fJ_2Flwd5Qugyltb_5mU2ALqtssaPqMdy_5-xN4). This ties us further into a specific third party and could be complicated to build, but it offers the simplest/most efficient request process:

  ```
  > https://image-service/v2/images/raw/fticon:cross?format=png
  [ proxies to ]
  > https://third-party/uploaded/fticon/cross?format=png
  ```

As well as reimplementing what we already have in Image Service v1, we also need to allow versioning of image sets. Currently we have no ability to remove images as it would result in dependent sites breaking. We'd like to support a version in the custom scheme like this:

```
fticon-v4:cross
fticon-v5:cross
```

This complicates all of the above options, probably equally.

**Comment by rowanmanning** [comment]
An update on this. We're going with option 2 above and that's what's being worked on. I think an S3 bucket is probably the best place for the images to live, but that can be decided on properly later.

The Image Service itself will translate custom schemes to point to a new hostname, and the directory structure on the new server will map to the scheme. E.g:

```
fticon:bell      ->  https://newhost/fticon/unversioned/bell.svg
fticon-v5:bell   ->  https://newhost/fticon/v5/bell.svg
fticon:sub/bell  ->  https://newhost/fticon/unversioned/sub/bell.svg
```

As you can see above, we'll also be allowing versioned schemes. You can specify a major version only (in a similar way to API versions) by adding `-vX` to the end of the scheme.

E.g. these are valid:

```
fticon:bell
fticon-v4:bell
fticon-v5:bell
```

And these are invalid:

```
fticon-4:bell     <-  No "v" to specify version
fticon-v5.0:bell  <-  Trying to specify a minor version
fticon-v^5:bell   <-  Version is not semver, unlike the build service
```

**Comment by alicebartlett** [comment]
This seems good to me @rowanmanning.

WRT versioning... I think we shouldn't tie fticon version to the major version of o-icons. o-icons has some Sass which we could make a major version change to without changing any of the actual icons, at which point we'd either have to do a major release of fticon, or have the two numbers diverge.

It's a bit confusing having o-icons@v4.x.x correspont to fticon-v2 but I think that is a better solution.
