### ISSUE TITLE
Update healthcheck to v1.1

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-image-service#118]
http://healthcheck.ft.com/validate?host=www.ft.com&server=www.ft.com%2F__origami%2Fservice%2Fimage&protocol=https

**Comment by rowanmanning** [comment]
Just a note: this requires work in [n-express](https://github.com/Financial-Times/n-express). Might be a breaking change, I'm not sure, depends on whether the healthcheck app will suddenly start failing all of the Next apps with validation errors

**Comment by JakeChampion** [comment]
We are now using healthcheck v1.1 🎉
