### ISSUE TITLE
Cloudinary fetch api issue

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-image-service#153]
They don't like urls above 256 characters when requested via their fetch api as they use the url as the ID in their database and they set their ID to have a max length of 256 characters. This breaks images for markets-data, ft-email-manual and possibly many other products.

More information about this error -- https://support.cloudinary.com/hc/en-us/articles/207746165-Why-do-I-get-a-public-ID-too-long-error-when-trying-to-fetch-from-a-remote-URL-

We should either fix this breaking change or document it in our migration guide.

**Comment by JakeChampion** [comment]
Cloudinary have increased the id length to 1024 characters which solves most of our issues however we have seen image requests with url lengths above 1700 characters (ft-email-manual) which will still fail using the new image service. We are talking to cloudinary about how to resolve this situation.

**Comment by rowanmanning** [comment]
This seems to be solved, we can come back to it if we stumble across any images with longer URLs.
