### ISSUE TITLE
Work out whether we need the FT-Image-Format header code

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#163]
Currently we set the `FT-Image-Format` header in [`lib/image-service.js`](https://github.com/Financial-Times/origami-image-service/blob/master/lib/image-service.js). We might not need to do this, as we're already setting these in the CDN. We need to do some testing around this.

This can be ignored if we end up setting our own cache keys as outlined in #57.

**Comment by Limess** [comment]
Based on 

> This can be ignored if we end up setting our own cache keys as outlined in #57.

and in #57

> Images now have unique cache keys used to purge them from the cache. We also have cache keys for whole schemes, cache keys for image type and a cache key for all images.

I'd take a punt and say this is invalid and can be closed.
