### ISSUE TITLE
Support next-assets

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/origami-image-service#180]
I'm working on getting anything that isn't an image moved elsewhere, and for now, serving all images held in https://github.com/Financial-Times/next-assets from www.ft.com/__assets/creatives

It'd be nice if image-service supported theses as a first class collection e.g. `www.ft.com/__origami/service/image/v2/creatives:path/to/creative`

**Comment by rowanmanning** [comment]
I was talking about this earlier with Jake, and yeah it'd be good if it was a first-class citizen of the Image Service. We'd want to perform an audit of this repo first though – there are things that should really already be in one of the other image sets.

E.g. https://github.com/Financial-Times/next-assets/blob/master/public-src/icons/fastft.svg should be in https://github.com/Financial-Times/logo-images

We want to avoid adding a dumping ground of images, so some tidying would be necessary.

**Comment by rowanmanning** [comment]
Just had another quick discussion, it might actually be a better idea to create a new image set repo and migrate things across bit by bit. That way we can be sure that images go to the right places and also we lose all the images that aren't used.

**Comment by wheresrhys** [comment]
Maybe copy all the stuff worth keeping from this to a new repo - o-creative-images or something - then wind down use of this repo and the /__assets/creatives url pattern

**Comment by rowanmanning** [comment]
I don't think we're gonna get around this, and nobody else in Customer Products has asked for it. I'm gonna close
