### ISSUE TITLE
webp charts compress with artefacts and blurry text

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-image-service#183]
example image --> https://www.ft.com/__origami/service/image/v2/images/raw/ftcms:81b19d2c-b862-11e6-ba85-95d1533d9a62?source=next

need to contact cloudinary and see if anything can be done to address the compression issue.

**Comment by rowanmanning** [comment]
This has been reported again, with the chart here being blurry:

![blurry chart](https://www.ft.com/__origami/service/image/v2/images/raw/http%3A%2F%2Fwww.ft.com%2Ffastft%2Ffiles%2F2017%2F02%2Fnewcar.png?source=next&fit=scale-down&width=700)

Explicitly setting to PNG and upping quality doesn't seem to do anything:

![blurry chart that shouldn't be](https://www.ft.com/__origami/service/image/v2/images/raw/http%3A%2F%2Fwww.ft.com%2Ffastft%2Ffiles%2F2017%2F02%2Fnewcar.png?source=next&fit=scale-down&width=700&quality=lossless&format=png)

**Comment by JakeChampion** [comment]
This is fixed by setting a higher dpr than 1 onto the transform, there is no work to be done on Cloudinary's side

normal dpr
https://www.ft.com/__origami/service/image/v2/images/raw/https%3A%2F%2Fd6c748xw2pzm8.cloudfront.net%2Fprod%2F7ab35850-a1c3-11ea-ac3d-73fb6b7b1ece-standard.png?fit=scale-down&quality=highest&source=next&width=700

2x dpr 
https://www.ft.com/__origami/service/image/v2/images/raw/https%3A%2F%2Fd6c748xw2pzm8.cloudfront.net%2Fprod%2F7ab35850-a1c3-11ea-ac3d-73fb6b7b1ece-standard.png?fit=scale-down&quality=highest&source=next&width=700&dpr=2
