### ISSUE TITLE
Gravity parameter supporting basic directions

### ISSUE THREAD

**Issue by wodor** [Financial-Times/origami-image-service#190]
It would be great if image service could cut images not only at center but also honour gravity suggestion. 

'NorthWest', 'North', 'NorthEast', 'West', 'Center', 'East', 'SouthWest', 'South', 'SouthEast' 
similar to this 
http://www.rubydoc.info/github/jnicklas/carrierwave/CarrierWave%2FMiniMagick%3Aresize_to_fill

**Comment by rowanmanning** [comment]
As mentioned in out meeting, we'll consider adding this feature after some testing with How to Spend It images. Thanks for raising 👍

**Comment by JakeChampion** [comment]
No one is asking for this feature anymore, closing the issue.

If an FT product does want this feature, please open a new issue 👍
