### ISSUE TITLE
404ing images on registry

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-image-service#233]
404-ing images which do exist in the git repo but not in the image service -- http://registry.origami.ft.com/components/origami-brand-images@1.0.2

Because they are being requested as png when they are gif extension -- https://www.ft.com/__origami/service/imageset-data/ftbrand/v1/ft-data.png
https://www.ft.com/__origami/service/imageset-data/ftbrand/v1/ft-data.gif

https://github.com/Financial-Times/origami-brand-images/blob/master/src/ft-data.gif

https://github.com/Financial-Times/origami-brand-images/blob/master/imageset.json#L22

I assume the registry does not use the extension field within the image.json file?

**Comment by onishiweb** [comment]
It doesn't, good spot!

**Comment by rowanmanning** [comment]
I'm looking into fixing this image-service side. There have been updates to all of the imagesets, now I just need to remove explicit file extensions from the Image Service.

- [ ] Image Service work
- [x] https://github.com/Financial-Times/fticons/pull/30
- [x] https://github.com/Financial-Times/headshot-images/pull/39
- [ ] https://github.com/Financial-Times/logo-images/pull/19
- [ ] https://github.com/Financial-Times/o-icons/pull/53
- [ ] https://github.com/Financial-Times/origami-brand-images/pull/5
- [ ] https://github.com/Financial-Times/origami-specialist-title-logos/pull/5
- [ ] https://github.com/Financial-Times/podcast-logos/pull/2
- [x] https://github.com/Financial-Times/social-images/pull/11
- [x] https://github.com/Financial-Times/social-images/pull/12

**Comment by rowanmanning** [comment]
This should be fixed now on QA. Will promote today and reopen if there's anything else that needs doing.
