### ISSUE TITLE
The Surrogate-Key header can be invalid

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#239]
Currently on master the `Surrogate-Key` header can be invalid (contain invalid characters). We promoted to production and then rolled back when [this error](https://sentry.io/nextftcom/origami-image-service-producti/issues/233753147/events/5060331195/) started coming in.

This is replicable locally with the following URL:
<http://localhost:8080/v2/images/raw/http%3A%2F%2Fs3-eu-west-1.amazonaws.com%2Ffthtsi-assets-production%2Fez%2Fimages%2F0%2F9%2F3%2F2%2F1212390-1-eng-GB%2FY+et+Beaute%CC%81+Tranquille.jpg?dpr=2&width=300&format=jpg&uri=http%3A%2F%2Fs3-eu-west-1.amazonaws.com%2Ffthtsi-assets-production%2Fez%2Fimages%2F0%2F9%2F3%2F2%2F1212390-1-eng-GB%2FY%2Bet%2BBeaute%CC%81%2BTranquille.jpg&height=300&source=htsi>

Commenting out this line fixes it, illustrating that the Surrogate-Key header is the issue:
https://github.com/Financial-Times/origami-image-service/blob/master/lib/image-service.js#L155

**Comment by JakeChampion** [comment]
Closed by #238
