### ISSUE TITLE
Investigate whether fastly can do immutable caching

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#252]
And implement if we can for ftcms images. We're currently seeing more requests than we should for ftcms images (which have a cache time of one year). As ftcms URLs should be immutable, we don't want to see any Fastly requests for them.

**Comment by JakeChampion** [comment]
Spoken with Fastly _(Patrick :-D )_, they do not support `cache-control: Immutable`, they have a ticket for it but no expected date on when/if it will go live.
