### ISSUE TITLE
Add a Cloudinary dashboard to our screen

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#256]

**Comment by rowanmanning** [comment]
I started looking at building this into the service itself, but Cloudinary's API only provides single usage/total values for each metric rather than all the data we'd need to make a graph.

**Comment by JakeChampion** [comment]
How about pinging the data into graphite and creating dashboards using grafana?

**Comment by rowanmanning** [comment]
We don't have a screen
