### ISSUE TITLE
Re-add the test page from the image service tests?

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#3]
It might be useful to keep a page which tests images in different services (like this https://origami-image-service-tests.herokuapp.com/). The [repo is available here](https://github.com/financial-times/origami-image-service-tests).

This should compare v1 and v2 of the Image Service, and ideally be powered by JSON so that we can easily add more images in future. `n-express` includes handlebars so I imagine that will be doable.

In terms of URLs, maybe this should just sit on `/compare`? That way if a v3 is ever built we can continue adding to it.

**Comment by alicebartlett** [comment]
Side by side comparison for the old image service vs the new image service

**Comment by rowanmanning** [comment]
@mariabg added in #42
