### ISSUE TITLE
Stop using images we don't control in the integration tests

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#305]
(except where we can't, e.g. CMDB scheme images)

**Comment by JakeChampion** [comment]
I think we have only one image left which is not controlled by either Origami or UPP -- http://s3-eu-west-1.amazonaws.com/fthtsi-assets-production/ez/images/0/9/3/2/1212390-1-eng-GB/Y+et+Beaute%CC%81+Tranquille.jpg
