### ISSUE TITLE
Tinted bookmark and bookmark-outline icons have different sizes

### ISSUE THREAD

**Issue by samuele-artuso** [Financial-Times/origami-image-service#323]
* `bookmark`: https://goo.gl/cJJG1d
* `bookmark-outline`: https://goo.gl/nCctSA

This bug reproduces only when using tints.

<details>
<summary>How they look on top of each other</summary>

<img src="https://user-images.githubusercontent.com/3853889/35740855-0b9e8d08-082e-11e8-8596-ff4bc8571335.png" width="300" />

</details>

**Comment by rowanmanning** [comment]
Ah I _think_ this looks like a caching issue, and we're gonna try clearing. Please don't add cache-busts to these yourself, but here are some cache-busted URLs which demonstrate the icons having the same widths:

### No tint

No outline: https://www.ft.com/__origami/service/image/v2/images/raw/fticon-v1:bookmark%3Fcachebust?source=o-icons&format=svg

Outline: https://www.ft.com/__origami/service/image/v2/images/raw/fticon-v1:bookmark-outline%3Fcachebust?source=o-icons&format=svg

### Tint

No outline: https://www.ft.com/__origami/service/image/v2/images/raw/fticon-v1:bookmark%3Fcachebust?source=o-icons&format=svg&tint=f00

Outline: https://www.ft.com/__origami/service/image/v2/images/raw/fticon-v1:bookmark-outline%3Fcachebust?source=o-icons&format=svg&tint=f00

**Comment by rowanmanning** [comment]
We've purged the old icons now, but that can take a short while to propagate. I'll check tomorrow morning and let you know when it's all fixed 🙂

**Comment by samuele-artuso** [comment]
Reopening as still experiencing the same issue.

**Comment by rowanmanning** [comment]
@samuele-artuso I think this is finally fixed! Sorry for the wait, could you confirm this is the correct wider image for you now?

Outlined: https://www.ft.com/__origami/service/image/v2/images/raw/fticon-v1:bookmark-outline?source=o-icons&tint=%23000000,%23000000&format=svg

Filled: https://www.ft.com/__origami/service/image/v2/images/raw/fticon-v1:bookmark?source=o-icons&tint=%23000000,%23000000&format=svg
