### ISSUE TITLE
Use the explicit API to clear the cache

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#329]
Based on our discussion with Cloudinary. Example snippet:
```
Cloudinary::Uploader.explicit("https://s3-eu-west-1.amazonaws.com/origami-build-service-v3-bundles/image.jpg",type:"fetch",invalidate:true)
```
[Docs](https://cloudinary.com/documentation/image_upload_api_reference#explicit).

**Comment by JakeChampion** [comment]
From https://github.com/Financial-Times/origami-image-service/issues/476
>We stopped using the fetch api and now use the upload api and set the filename to be the hash of the requested image. This approach means we no longer need to purge from cloudinary, we can purge from Fastly and then the next request will get the newly updated image which will have a different hash, meaning a different filename when we upload to cloudinary.

We can close this issue as fixed 👍
