### ISSUE TITLE
Consider using quality:auto

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#330]
This keeps coming up in meetings with Cloudinary. It should be possible for us to add this as an opt-in feature. See [quality parameter docs](https://cloudinary.com/documentation/image_transformation_reference#quality_parameter).

**Comment by JakeChampion** [comment]
I've considered using it but when I've tested quality:auto (several times our the last 2 years) it is always generating larger file sizes than our current preset of quality settings.
