### ISSUE TITLE
Complete __about endpoint information

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/origami-image-service#34]
Maria's PR adds most things, but we'll need to add the following URLs once we create them:
- [x] [Production Heroku app control panel](https://dashboard.heroku.com/pipelines/be91fac7-5b0e-40f5-abd1-b81b72ad1b97)
- [x] Production Pingdom checks ([EU](https://my.pingdom.com/newchecks/checks#check=2301115) and [US](https://my.pingdom.com/newchecks/checks#check=2301117))
- [x] [Production Sentry dashboard](https://sentry.io/nextftcom/origami-image-service-producti/)

Also set to bronze support level for now, while we're in beta.

[Here](https://github.com/Financial-Times/origami-image-service/tree/complete-about-info)'s a branch with all the added links so far

**Comment by alicebartlett** [comment]
(look at an n-express app to find out how next are doing this)

**Comment by rowanmanning** [comment]
We should include Pingdom checks in the `__about` endpoint:
- [Origami Navigation Service (HTTP)](https://my.pingdom.com/reports/uptime#check=2287222)
- [Origami Navigation Service (HTTPS)](https://my.pingdom.com/reports/uptime#check=2287223)

**Comment by rowanmanning** [comment]
Maria's PR adds most things, but we'll need to add the following URLs once we create them:
- Production Heroku app control panel
- Akamai CDN control panel
- Fastly CDN control panel
- Production Pingdom checks
- Production Sentry dashboard

**Comment by rowanmanning** [comment]
@mariabg we're not going to add the Fastly/Akamai control panels as these don't actually have any Image Service specific config. So your branch should be good to PR when you're ready :)
