### ISSUE TITLE
Bug: broken css on https://www.ft.com/__origami/service/image/v2

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-image-service#346]
## What
The css that gets loaded on https://www.ft.com/__origami/service/image/v2 returns a 404

## Details
The `base` element looks correct: `<base href="/__origami/service/image/"/>`
Perhaps the issue is with the link element?: `<link rel="stylesheet" href="/main.css" />`

<img width="1280" alt="screen shot 2018-12-19 at 14 25 45" src="https://user-images.githubusercontent.com/1569131/50226038-1396af00-039a-11e9-8fdf-d503cb6995b2.png">

**Comment by notlee** [comment]
Looks like this was fixed in QA but wasn't promoted to production. Doing that now. :)
