### ISSUE TITLE
update proxy-helper to use new image service

### ISSUE THREAD

**Issue by alicebartlett** [Financial-Times/origami-image-service#35]
(Do after shipping beta)

https://financial-times.github.io/responsive-image-proxy-helper/#?uri=http:%2F%2Fim.ft-static.com%2Fcontent%2Fimages%2Fa60ae24b-b87f-439c-bf1b-6e54946b4cf2.img&source=test&height=&width=

**Comment by rowanmanning** [comment]
This should be moved into the Image Service itself. I'm working on that, and will redirect the original application once I'm done.
