### ISSUE TITLE
URLs don't work in Gmail signatures

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/origami-image-service#383]
## What

The Origami Image Service does not work in Gmail email signatures.

## Details

I've tried using the image service in my email signature, with the following URL.

```
https://www.ft.com/__origami/service/image/v2/images/raw/ftlogo-v1%3Aft-text-pink?source=email&width=70&height=98
```

This is the result:

![image](https://user-images.githubusercontent.com/51677/57614332-e200c900-7570-11e9-87f1-1d3cc7ce0d18.png)

I think this is because Gmail uses its own proxy for third-party media. The URL is convert to (in this case)...

```
https://ci3.googleusercontent.com/proxy/kmCAnJ7GcwrjcBeo_bbPbR3WNslzPj1UpH_mhb6vj0_opzdsgywsrw-786V91BFvdSS-z5pZ1rE69f3zSimET5ofraJBh-1KAT-fi9aUvKyBmGCWQuciRtH5f1-5-J4HeU72aHk5harmkmpR5QyQkEgK7VFAVeMI_GFCxaRww6HR5TP5=s0-d-e1-ft#https://www.ft.com/__origami/service/image/v2/images/raw/ftlogo-v1%3Aft-text-pink?source=email&width=70&height=98
```

... by Gmail, which returns a 404 page.

**Comment by sjparkinson** [comment]
Adding `&format=png` looks to fix this though!

Do with this issue as you see fit.

**Comment by JakeChampion** [comment]
gmail does not support svg images, you need to convert it to png using `&format=png`
