### ISSUE TITLE
Write Akamai config

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#45]
While we'll be [using Fastly for the main CDN](https://github.com/Financial-Times/origami-image-service/issues/14), the original Image Service domain will still be routed through Akamai.

The only config we should need is to redirect the `/v2` path to the new `ft.com` address:

```
image.webservices.ft.com/v2/...  ->  ft.com/origami/service/image/v2/...
```

**Comment by JakeChampion** [comment]
This is written and deployed to staging, it will go live tomorrow.

**Comment by rowanmanning** [comment]
This is now deployed to live and working
