### ISSUE TITLE
Make the purging endpoint also purge from cloudinary

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-image-service#476]
Currently the purging endpoint only purge from fastly, we also need to purge from cloudinary for the situation where the original image has been updated.

This has come up now because fastcharts wants to be able to update a chart and have the update appear on any articles which embed the chart. The chart embeds go through the image service and when the charts are updated the url does not change.

**Comment by JakeChampion** [comment]
I don't think we can support Purging from Cloudnary without rebuilding our Cloudinary integration.
Invalidating the Cloudinary CDN takes minutes (although it might take up to an hour) and the invalidation doesn't work at all for how we use Cloudinary.
>By default, signed URLs (with or without versions) are not invalidated.

We use the Cloudinary Fetch API (Which is no longer documented on cloudinary.com/documentation) alongside Cloudinary Signed URLs. 

We likely need to stop using the Fetch API, which means we will no longer be able to offer the http scheme (The ability to use any image url and we will optimise the image and store it in our CDN).

**Comment by chee** [comment]
> We likely need to stop using the Fetch API, which means we will no longer be able to offer the http scheme (The ability to use any image url and we will optimise the image and store it in our CDN).

does this mean the issue is a WONTFIX?

**Comment by JakeChampion** [comment]
> > We likely need to stop using the Fetch API, which means we will no longer be able to offer the http scheme (The ability to use any image url and we will optimise the image and store it in our CDN).
> 
> does this mean the issue is a WONTFIX?

We stopped using the fetch api and now use the upload api and set the filename to be the hash of the requested image. This approach means we no longer need to purge from cloudinary, we can purge from Fastly and then the next request will get the newly updated image which will have a different hash, meaning a different filename when we upload to cloudinary.

We can close this issue as fixed 👍

**Comment by chee** [comment]
@JakeChampion does that affect either of these issues?:

https://github.com/Financial-Times/origami-image-service/issues/329

https://github.com/Financial-Times/origami-image-service/issues/434
