### ISSUE TITLE
Investigate removing/overhauling the BASE_URL option

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#54]
This is currently specified as an environment variable (introduced in #53) which allows us to run the application both at the root of a domain and a sub-path. There are two things I'd like to do:

1. Remove the `BASE_URL` option and calculate it based on request information
2. Use [the `<base/>` element](https://developer.mozilla.org/en/docs/Web/HTML/Element/base) in the views rather than manually adding to each URL

**Comment by JakeChampion** [comment]
Resolved via #56
