### ISSUE TITLE
Record metrics with StatsD

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#6]
Take cues from the [Build Service](https://github.com/Financial-Times/origami-build-service).

**Comment by rowanmanning** [comment]
This should be done by using n-express. Still needs testing

**Comment by alicebartlett** [comment]
n-express/n-metrics already in the project.
This ticket is mostly: 
- check this is working
- work out what we want to monitor in the image service + add monitoring

**Comment by rowanmanning** [comment]
Metrics are now being recorded for basic stuff, memory etc. We should work out what else we'd like to monitor soon.

**Comment by JakeChampion** [comment]
Some ideas:
- Resolutions/quality being requested
- Image type being requested
- Response time
- How long are optimisations taking

**Comment by rowanmanning** [comment]
FYI the Graphite dashboard I've got working [is viewable here](http://grafana.ft.com/dashboard/db/origami-image-service-v2)

**Comment by rowanmanning** [comment]
I think what we have is definitely enough for launching a public beta, so I'm going to remove it from the "public beta" milestone and we can add stuff when we need it.

**Comment by rowanmanning** [comment]
I don't think we're likely to do this any time soon. Can reopen if/when we decide to if necessary
