### ISSUE TITLE
Stop error hijacking on production

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#60]
Currently any error pages that the Image Service serves are hijacked, which means that they're not very useful to developers using the service. E.g.

- Production (not descriptive): http://ft.com/origami/service/image/v2/images/raw/http://www.elblogdelinfo.com/wp-content/uploads/alb_elias.jpg?source=alberto&width=400&height=hello
- QA (descriptive): http://origami-image-service-qa.herokuapp.com/origami/service/image/v2/images/raw/http://www.elblogdelinfo.com/wp-content/uploads/alb_elias.jpg?source=alberto&width=400&height=hello

We should fix this.

**Comment by JakeChampion** [comment]
This is now live! 🎉
