### ISSUE TITLE
Investigate the Fastly caching issues

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#64]
Currently we're seeing some odd caching behaviour, with our headers not being respected. Copied from @JakeChampion's message on Slack:

> ...We also found that the caching logic seems to hit our origin servers more often than it should. We've organised to have a chat with Keith Circel about this on Friday as he is currently away.
> 
> I think Falcon's VCL might be an issue, there cache hit ratio is not very good. It's very confusing why it isn't respecting our caching headers
> 
> as we specify to serve stale on error and whilst revalidating, both set to serve stale for upto a week
> 
> but that didn't happen
> 
> The same image request hit origin multiple times, however, not all the time ¯\_(ツ)_/¯

**Comment by JakeChampion** [comment]
We believe we are not getting amazing cache performance because hardly no-one is using the service. We will investigate this issue in the future when more people use the service and we have larger and more diverse data.

**Comment by JakeChampion** [comment]
Could not replicate.
