### ISSUE TITLE
Bug: placeholder api does not work with ftcms scheme

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-image-service#696]
## What
It looks like the new placeholder api does not get triggered for the ftcms scheme and instead the raw api is used. I'd assume this is something to do with how the routes/middleware is registered.

## Details
If you open a [placeholder for ftcms image](https://origami-image-service-qa.herokuapp.com/v2/images/placeholder/ftcms%3A3520df36-8c20-11e6-8cb7-e7ada1d123b1?source=jake&fit=cover&gravity=faces&format=png&quality=high) I would expect to see a placeholder image which contains the parameters in the request as text in an image.
What actually happens is the actual ftcms image is returned.
This doesn't look to be an issue with all placeholder api requests as it works correctly for the [ftflag scheme]( https://origami-image-service-qa.herokuapp.com/v2/images/placeholder/ftflag:eu?source=jake&fit=cover&format=png&quality=low)

**Comment by chee** [comment]
@JakeChampion when i open that ftcms url i see a placeholder image:
https://origami-image-service-qa.herokuapp.com/v2/images/placeholder/ftcms%3A3520df36-8c20-11e6-8cb7-e7ada1d123b1?source=jake&fit=cover&gravity=faces&format=png&quality=high

**Comment by chee** [comment]
![a screenshot of that url showing a placeholder](https://user-images.githubusercontent.com/178266/106447739-c262b000-6479-11eb-996b-6c10ab3d4d1f.png)
