### ISSUE TITLE
Odd SVG encoding

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#71]
Some SVGs seem to have encoding issues that aren't present in v1 of the Image Service. [Example](https://www.ft.com/origami/service/image/v2/images/raw/http%3a%2f%2fnext-geebee.ft.com%2fassets%2fbackgrounds%2ffront-page-section-header-v2.svg?source=rew).

---
**Update**

This seems to be a Cloudinary issue rather than anything wrong with our service. The original SVG doesn't have any odd characters at the end:

```sh
curl https://next-geebee.ft.com/assets/backgrounds/front-page-section-header-v2.svg
```

```svg
<svg width="4" height="4" viewBox="0 0 4 4" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 0h1v1H0z"/>
</svg>
```

But when requested via Cloudinary, it does:

```sh
curl http://res.cloudinary.com/financial-times/image/fetch/f_svg/http://next-geebee.ft.com/assets/backgrounds/front-page-section-header-v2.svg
```

```svg
<svg width="4" height="4" viewBox="0 0 4 4" xmlns="http://www.w3.org/2000/svg">
    <path d="M0 0h1v1H0z"/>
</svg>≤v≈êΩ,l
```

**Comment by JakeChampion** [comment]
curl https://image.webservices.ft.com/v1/images/raw/http%3a%2f%2fnext-geebee.ft.com%2fassets%2fbackgrounds%2ffront-page-section-header-v2.svg?source=rew

curl https://www.ft.com/origami/service/image/v2/images/raw/http%3a%2f%2fnext-geebee.ft.com%2fassets%2fbackgrounds%2ffront-page-section-header-v2.svg?source=rew

**Comment by MaorGariv** [comment]
Hi,

A fix for this issue was just deployed:)
It shouldn't append characters to the end of the file now.

**Comment by rowanmanning** [comment]
Hi @MaorGariv. We're still having issues with the same SVG mentioned above, there are still odd characters at the end of the file when you run

```sh
curl http://res.cloudinary.com/financial-times/image/fetch/f_svg/http://next-geebee.ft.com/assets/backgrounds/front-page-section-header-v2.svg
```

I've tried removing the image from Cloudinary via the admin interface and loading it again, but this hasn't fixed it.

**Comment by MaorGariv** [comment]
Hi @rowanmanning ,

We've deleted the resource from your Media library and tried again - it works properly now.
Can you please retry and confirm the same on your end as well?

**Comment by JakeChampion** [comment]
Hi @MaorGariv, I can confirm it works now :-) 🎉  Thanks!

**Comment by rowanmanning** [comment]
Yay 🎉 thanks @MaorGariv. Closing this now
