### ISSUE TITLE
Some responses are 400ing when cloudinary response is ok

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-image-service#72]
Example url - https://origami-image-service-eu.herokuapp.com/origami/service/image/v2/images/raw/http%3A%2F%2Fassets1.howtospendit.ft-static.com%2Fimages%2F6c%2Fcd%2Fce%2F6ccdce84-22d1-4a7f-be76-3ece7fecb314_grid_crop.png?width=300&height=300&source=howtospendit

cloudinary url - http://res.cloudinary.com/financial-times/image/fetch/c_fill,f_png,h_300,q_72,w_300/http://assets1.howtospendit.ft-static.com/images/6c/cd/ce/6ccdce84-22d1-4a7f-be76-3ece7fecb314_grid_crop.png

**Comment by rowanmanning** [comment]
I'm struggling to replicate this, I can't get the example URL to 400 at all. I wonder whether we need to reload the big page of images to get this working?

**Comment by JakeChampion** [comment]
As am I :/

**Comment by JakeChampion** [comment]
Moving to after the beta as we need more data to verify this issue.

**Comment by rowanmanning** [comment]
This seems to be fixed
