### ISSUE TITLE
Let's confirm origami image service will work with origami spec v2 image sets

### ISSUE THREAD

**Issue by JakeChampion** [Financial-Times/origami-image-service#722]
The image sets are installed as dependencies at their latest version, we should migrate an imageset component to the origami v2 spec and release it as a beta and then see if we need to make any changes in the image service to use that new version of the imageset

**Comment by chee** [comment]
they are already installing the imagesets via npm. the imagesets have no JS and no scss and no dependencies. (they have a devDependency).
they will continue to work.

let's move the imagesets into the image-service, they have no reason to be components.

**Comment by JakeChampion** [comment]
> let's move the imagesets into the image-service, they have no reason to be components.

Yes, this is a great idea Chee 😄
