### ISSUE TITLE
Change compression level when dpr is applied

### ISSUE THREAD

**Issue by rowanbeentje** [Financial-Times/origami-image-service#73]
I discussed this last week with Jake but worth explicitly raising here; after comparing a few images side-by-side with the v1 images, noticed that the new service was producing images that were much larger.  Looking more closely, a substantial part of this seems to be only when the `dpr` value is set - the old service substantially increased the compression level when dpr was applied.

This is hinted at in the old documentation (not yet ported?):

>Device Pixel Ratio, i.e. number of image pixels per CSS pixel. The default is 1, which gives the standard 1:1 ratio of image pixels to CSS pixels. Set to 2 for high-DPI ("Retina") displays. Request to the image service with width=100&dpr=2 will output image 200 pixels wide, but optimized to be displayed with CSS width:100px
>Note that browsers don't automatically adjust intrinsic size of images with higher DPI, so you need'll need to use some "responsive image" solution, e.g. set explicit width or height, use image-set() or srcset attribute.

Comparing images from v1, using the additional DPR images Jake added last week:
https://image.webservices.ft.com/v1/images/raw/ftcms:2dac88f0-b273-4e48-9c7d-9078db39db55?source=app&width=1000&fit=scale-down - 1000px wide, dpr 1 - **144k**
https://image.webservices.ft.com/v1/images/raw/ftcms:2dac88f0-b273-4e48-9c7d-9078db39db55?source=app&width=500&fit=scale-down&dpr=2 - 1000px wide, dpr2 - **96k**

From v2:
https://www.ft.com/origami/service/image/v2/images/raw/ftcms:2dac88f0-b273-4e48-9c7d-9078db39db55?source=app&width=1000&fit=scale-down - 1000px wide, dpr 1 - **192k**
https://www.ft.com/origami/service/image/v2/images/raw/ftcms:2dac88f0-b273-4e48-9c7d-9078db39db55?source=app&width=500&fit=scale-down&dpr=2 - 1000px wide, dpr 2 - **192k**

(Do the visual compression levels approximately match otherwise?  Significantly larger images anyway, but I'll raise a separate issue for that if necessary)

**Comment by rowanmanning** [comment]
The work in #91 gets us some of the way towards solving this. We may be able to tweak compression levels a bit more in a later PR.

Using the image `ftcms:2dac88f0-b273-4e48-9c7d-9078db39db55` and the transform `width=500&fit=scale-down&dpr=2`:

<dl>
<dt>Image Service V1</dt>
<dd>~94k</dd>
<dt>Image Service V2</dt>
<dd>~112k</dd>
<dt>Image Service V2 (browser with WebP support)</dt>
<dd>~119k</dd>
</dl>

As an aside, I'm not sure why the WebP versions are larger. I'll investigate that separately.

**Comment by rowanmanning** [comment]
Cool, this is on production now. Gonna close this issue but we'll probably be constantly trying to make file-size improvements. Thanks for reporting :)
