### ISSUE TITLE
Update Supplier DB

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#80]
Record supplier, contact, and SLA information in Salesforce. We're waiting for the contract with Cloudinary to be finalised before we can do this. We'll also need to link to the supplier info in [the run book](https://sites.google.com/a/ft.com/ft-technology-service-transition/home/run-book-library/origami-image-service-v2) as part of this work.

**Comment by alicebartlett** [comment]
(Waiting for procurement process to complete before I do this!)

**Comment by alicebartlett** [comment]
Procurement is now complete. I spoke to the PMO, and it is their job to update the supplier db so I'll leave that with them. Once they have added Cloudinary to their db we'll still need to add a link to it to the run book.

**Comment by rowanmanning** [comment]
We'll update the runbook post-launch.

**Comment by rowanmanning** [comment]
Supplier has been added (https://financialtimes.my.salesforce.com/a0zD000000G9u1E), and I've linked to it in the runbook.
