### ISSUE TITLE
Write a runbook

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/origami-image-service#82]
See [the v1 runbook](https://sites.google.com/a/ft.com/ft-technology-service-transition/home/run-book-library/origami-image-service-run-book) and work from there.

**Comment by JakeChampion** [comment]
The system-code is `origami-image-service-v2`. Once the new image service is out of the door, we can change the system code of the old image service from `origami-image-service` to `origami-image-service-legacy` and the new image service from `origami-image-service-v2` to `origami-image-service`.

**Comment by rowanmanning** [comment]
I've started writing a runbook here: https://sites.google.com/a/ft.com/ft-technology-service-transition/home/run-book-library/origami-image-service-v2

**Comment by rowanmanning** [comment]
@alicebartlett, @JakeChampion, can you review [the run book](https://sites.google.com/a/ft.com/ft-technology-service-transition/home/run-book-library/origami-image-service-v2) for me? I've copied most of the information from the [v1 runbook](https://sites.google.com/a/ft.com/ft-technology-service-transition/home/run-book-library/origami-image-service-run-book).

**Comment by JakeChampion** [comment]
Reviewed, all looks good, we will need to update the supplier information once we have it.

**Comment by alicebartlett** [comment]
:+1:
